### ISSUE TITLE
Include the constituency ID in the CSV output

### ISSUE THREAD

**Issue by hubgit** [robfarr/UK-General-Election-2015-Data#3]
As the BBC uses the ONS identifier for each constituency, it would be very useful to have that ID in the output CSV file so it can be easily merged with other data.

**Comment by robfarr** [comment]
I am happy to add this feature - it shouldn't be too difficult as the data is already on the webpages being parsed.

**Comment by robfarr** [comment]
Feature implemented and merged into the master branch.

**Comment by hubgit** [comment]
Excellent, thanks :)
